---
- name: Run Shell - Run kubeadm to initiate the cluster
  ansible.builtin.shell: set -o pipefail && sudo kubeadm init | grep "kubeadm join"
  register: kube_worker_registration
  ignore_errors: false
  changed_when: kube_worker_registration.rc != 0

# With the fact cached, it creates two sets. One host var and one "ansible_fact".
- name: Set Fact - Set the output to an Ansible var.
  ansible.builtin.set_fact:
    worker_registration: "{{ kube_worker_registration.stdout }}"
    cacheable: true
